### ISSUE TITLE
脚本执行失败

### ISSUE THREAD

**Issue by nzyone** [0604hx/ViewUI-doc-offline#1]
给我邮箱发一份离线的文档可以吗？2598049398@qq.com，十分感谢🙇‍。

**Comment by 0604hx** [comment]
> 给我邮箱发一份离线的文档可以吗？[2598049398@qq.com](mailto:2598049398@qq.com)，十分感谢🙇‍。

邮件已发。

方便的话，麻烦提供下脚本执行失败的日志输出

**Comment by nzyone** [comment]
感谢您的回复，问题已经解决了，只是换了台电脑执行就可以了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 下午3:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [0604hx/ViewUI-doc-offline] 脚本执行失败 (Issue #1)





  
***@***.***，十分感谢🙇‍。
  
邮件已发。
 
方便的话，麻烦提供下脚本执行失败的日志输出
